### ISSUE TITLE
Navigation Tray Component

### ISSUE THREAD

**Issue by jahorwitz** [jahorwitz/mu-methods#14]
Acceptance Criteria:

- A navigation tray component exists (see screenshot)
- The navigation tray has a namespace with a component for the links that go into the tray
- The links should accept an icon and a path to route to
- React Router has already been set up for the application, but this component should employ `useRouter` in order to navigate between pages
- Automated Tests exist for the component
- Component is documented in Storybook

![Image](https://user-images.githubusercontent.com/29721136/213949292-dc85bc27-e16e-4844-a63e-cd525ea194cb.png)

![Image](https://user-images.githubusercontent.com/29721136/213949299-606b8b29-92a0-4f5e-9e08-9eacdcfcb477.png)

**Comment by kamal-ganiev** [comment]
Successfully reviewed and merged to the main branch
