### ISSUE TITLE
RFC-Vite-plugin-babel-macros for Styled Components

### ISSUE THREAD

**Issue by kehrenclou** [jahorwitz/mu-methods#55]
### RFC: Would like to consider adding this plug in so we can read styled components ClassNames in dev tools.

**NPM documentation and installation instructions**:  
[https://www.npmjs.com/package/vite-plugin-babel-macros](https://www.npmjs.com/package/vite-plugin-babel-macros)

**Implementation:**
`import styled from "styled-components/macro"`

Example:
yellow highlighted shows the results of using `import styled from "styled-components/macro"`
![image](https://user-images.githubusercontent.com/98502327/217105391-522e2a2e-4bc2-4d80-8b34-cf2fb5179d9d.png)

**Comment by jahorwitz** [comment]
Approved 👍 Feel free to make a PR to add this
