### ISSUE TITLE
SPIKE: Investigate and document potential solutions for camera permissions / components

### ISSUE THREAD

**Issue by jahorwitz** [jahorwitz/mu-methods#8]
Acceptance Criteria:

- A request for comments (RFC) issue has been opened and approved
- The RFC document describes the proposed solution including:
   - any libraries we will use
   - examples of usage
   - any risks associated with this proposal
- After approval of RFC, a detailed user story with acceptance criteria for implementing this component

**Comment by colburncodes** [comment]
**Demo** https://codepen.io/mozmorris/pen/JLZdoP****

**Npm package library** https://www.npmjs.com/package/react-webcam

**Github** https://github.com/mozmorris/react-webcam

**The Constraints**
We can build a constraints object by passing it to the videoConstraints prop. This gets passed into getUserMedia method. Please take a look at the MDN docs to get an understanding how this works.

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints

**Comment by colburncodes** [comment]
**RFC: Universal Camera component for React. Mobile first camera component for React.**
Designed with a focus on Android and iOS cameras. Works with standard webcams as well.

**NPM:** https://www.npmjs.com/package/react-camera-pro

**Demo:** https://purple-technology.github.io/react-camera-pro/

**MDN Docs:**
[developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia)

Github: https://github.com/purple-technology/react-camera-pro#readme

**USAGE** 
```
import React, { useState, useRef } from "react";
import {Camera} from "react-camera-pro";

const Component = () => {
  const camera = useRef(null);
  const [image, setImage] = useState(null);

  return (
    <div>
      <Camera ref={camera} />
      <button onClick={() => setImage(camera.current.takePhoto())}>Take photo</button>
      <img src={image} alt='Taken photo'/>
    </div>
  );
}

export Component;
```

**Comment by colburncodes** [comment]
**RFC: A React component that renders a preview for the device's either front or back camera. Camera's parameters like zoom, auto focus, white balance and flash mode are adjustable. With expo-camera, one can also take photos and record videos that are saved to the app's cache. Morever, the component is also capable of detecting faces and bar codes appearing on the preview.**

NPM: https://www.npmjs.com/package/expo-camera

**API Documentation**: https://docs.expo.dev/versions/latest/sdk/camera/

**Configure for IOS**
```
<key>NSCameraUsageDescription</key>
<string>Allow $(PRODUCT_NAME) to use the camera</string>
<key>NSMicrophoneUsageDescription</key>
<string>Allow $(PRODUCT_NAME) to use the microphone</string>
```

**Configure for Android**
```
<!-- Added permissions -->
<uses-permission android:name="android.permission.CAMERA" />

<!-- Optional permissions -->
<uses-permission android:name="android.permission.RECORD_AUDIO" />
```

**Comment by colburncodes** [comment]
You must request permission to access the user's camera before attempting to get it. To do this, you will want to use the [Permissions](https://docs.expo.dev/versions/v47.0.0/sdk/permissions/) API. You can see this in practice in the
